package JavaTopics;

public class A2_JavaTheory {

	// procedure oriented language-program can be breaken to steps,and there is no security because there are no access modifiers.
	
	// change is only constant in software industry,since java keep on updating frequently,java has more life in this IT industry.
	
	/*
	 * Java is simple no pointers,no multiple inheritance.
	 * Java is platform independent.
	 * Java is architectural neutral, that is change in upgrading of OS,ram etc ,wont effect java program.
	 * Java is portable,(example mobile portability-you change SIM without changing number),java program can migrate
	   from windows to Linux.
	    
	 *Java byte code is secure,because before execution of machine code, JVM will check whether byte code/.class file is
	  generated by valid compiler or not and properly formatted or not using magic number and other concepts.if any thing 
	  wrong it will give verify error,byte code verifier is responsible for this.
	  
	 * Java is OOP language.
	 
	 
	 * Java is inbuilt support for multi threading using API,by default JVM will run program single threaded,to make
	   multi threaded we have to write code explicitly.
	   
	 * Any technology if it is good at two main areas it is said to be ROBUST 1. Exception Handling 2. Memory Allocation.
	   java is strongly typed,no memory problem -garbage collector takes care,no abnormal termination because of exception handling,
	   platform independent.because of this facilities the chance of failing the program at runtime is very less,so java is robust.
	   
	 * Java is both compiled and interpreted ,first java compiler converts .java to machine independent byte code,
	   at run time JVM acts as interpreter and converts this byte code to machine code and executes that machine code.
	   All scripting languages like python,java script are only interpreted.
	   
	 * Java is dynamic that is load .class only on  demand.at runtime if JVM required any class then only the 
	   corresponding .class file will be loaded(Dynamic/Lazy loading).main advantage is program will always get latest .class
	   file and memory utilization will be improved.  
	   
	  * Java is high performance,distributed.  
	 */

	/*
	 * JDK -Java development kit ,JDK provides a set of tools like compiler, editor and debugger.
	 * JRE-Java Run time environment ,to run java programs.
	 * JVM -interpreter ,runs program line by line.
	 * JDK=JRE+development tools.
	 * JRE=JVM+Library tools.
	 */
	
}
